### ISSUE TITLE
build error when installing via luarocks

### ISSUE THREAD

**Issue by les-citrons** [tami5/sqlite.lua#115]
```
% luarocks install sqlite
Installing https://luarocks.org/sqlite-v1.0.0-0.src.rock

sqlite v1.0.0-0 depends on luv (1.41.1-0 installed)

Error: Build error: Failed installing /lua/sqlite/tbl/cache.lua in /home/raven/.local/lib/luarocks/rocks-5.3/sqlite/v1.0.0-0/lua/sqlite/tbl/cache.lua: /lua/sqlite/tbl/cache.lua: No such file or directory
```

**Comment by tami5** [comment]
Indeed it's a bug, I got similar fail `cp: cannot stat '/lua/sqlite/utils.lua': No such file or directory` I'm looking into it

**Comment by tami5** [comment]
@les-citrons thanks for reporting. It should now be fixed. Try to rerun the command.

 I'm going to keep this open until I fix the issue for future release.

**Comment by les-citrons** [comment]
ah thanks! it does work now!
