### ISSUE TITLE
SSH troubles

### ISSUE THREAD

**Issue by fdschmidt93** [tami5/sqlite.lua#134]
Hi there :)

apologies for the somewhat uninformed issue, but I'm not entirely sure why `telescope-smart-history` (due to `sqlite.lua`) wouldn't work on the remote machines I work on.

```lua
require "ffi".load("libsqlite3") -- seems to work as it returns userdata, should be fine, no?
```

But I always get the error "couldn't connect to sql database" when selecting an entry or closing the picker (ie `smart-history` wants to write the prompt to the database).

```lua
-- relevant telescope.setup { ... }

    history = {
      path = vim.env.HOME .. "/.local/share/nvim/databases/telescope_history.sqlite3", -- I guess should be fine
      limit = 100,
    },
```

Not sure anymore whether it was required on all servers (I'm finally asking for help after the 3rd time :sweat_smile: ), but I've downloaded `sqlite3` from https://www.sqlite.org/download.html and compiled to `HOME_PREFIX` `.local` which should be adequately in path (not even 100% sure whether all that is required, since `clib` is in fact found).

It's quite the nuisance cloning configs to the remote machines and then `telescope-smart-history` (which I like a lot) renders my config unusable. I'm not 100% sure whether there is any user rights problem, but it wouldn't seem obvious to me as I  can write to `history` path.

Any pointers would be very much appreciated, thanks in advance :)

**Comment by tami5** [comment]
hey @fdschmidt93. This is an issue I experienced multiple times and perhaps smart-history should just work regardless of sqlite being installed or setup correctly through falling to manual version.


I'm on mobile right now but my best guess would be that databases directory is not created yet maybe try having the database path point to .local/share/nvim/db.db instead?

**Comment by fdschmidt93** [comment]
Oh je, it really just seems to boil down to the folder not having been created. Thanks @tami5 :)

**Comment by tami5** [comment]
> Oh je, it really just seems to boil down to the folder not having been created. Thanks @tami5 :)

should we open a pr to create this subdirectory as a convention to where dbs should be located?
